Added a command prompt with CTRL+K
quentinguidee/sh-cloud-client pull request #2
Opened 2022-06-23 15:33 UTC by Lauryy06

![image](https://user-images.githubusercontent.com/80424145/175336006-b0fc1f35-de49-4842-a820-9283f7ed6537.png)

Same behavior as in (for example) Visual Studio Code. There is :
- Arrow navigation between commands (cyclic)
- Commands filtering
- Enter or click to run command

I've added a "tooltip" field in the `Command` interface, but I don't know the best way to display them, and maybe it's possible to animate the appearance/disappearance of the command prompt.

2022-06-23 15:52 UTC, Syycorax requested changes

2022-06-23 15:52 UTC, Syycorax commented on src/Assets/shadows.sass
> +    box-shadow: rgba(0, 0, 0, 0.1) 0 4px 12px
```suggestion
    box-shadow: rgba(0, 0, 0, 0.1) 0 4px 12px
    
```
Add newline at the end of file

2022-06-23 15:52 UTC, Syycorax commented on src/Components/CommandPrompt/CommandPrompt.module.sass
> +                font-weight: bold
```suggestion
                font-weight: bold
                
```
Add newline at the end of file

2022-06-23 15:52 UTC, Syycorax commented on src/Models/Command.tsx
> +};
```suggestion
};

```
Add newline at the end of file

2022-06-23 16:31 UTC, quentinguidee requested changes

2022-06-23 16:31 UTC, quentinguidee commented on src/Components/CommandPrompt/CommandPrompt.module.sass
> +                font-weight: bold
```suggestion
                font-weight: $weight-bold
```

2022-06-23 16:31 UTC, quentinguidee commented on src/Components/CommandPrompt/CommandPrompt.module.sass
> +    z-index: 1000
```suggestion
    z-index: 20
```

2022-06-23 16:31 UTC, quentinguidee commented on src/Components/CommandPrompt/CommandPrompt.tsx
> +    shown: boolean
```suggestion
    shown: boolean;
```

2022-07-01 09:13 UTC, Lauryy06 commented
See #13

2022-07-01 09:13 UTC, closed without merging